In [1]:
from proj1_helpers import *
import matplotlib.pyplot as plt
import numpy as np
from implementation import *
from Visualization import *
from data_preproc import preprocessing
from features_func import generate_features
from Learning import learning

In [2]:
train_path = 'data/train.csv'
y, tX, ids = load_csv_data(train_path, sub_sample=False)
nSample_tr, nFeature_tr = tX.shape

test_path = 'data/test.csv'
_, tX_te, ids_te = load_csv_data(test_path, sub_sample=False)
y_te = np.zeros((tX_te.shape[0],))
nSample_te, nFeature_te = tX.shape

complete_tX = np.vstack((tX,tX_te))
complete_y = np.append(y,y_te)
complete_ids = np.append(ids,ids_te)

model0, model1, model2 = preprocessing(complete_tX,complete_y,complete_ids)

all_model = [model0, model1, model2]


lambda_ = [np.logspace(-7, -6, 3), np.logspace(-7, -6, 3), np.logspace(-7, -6, 3)]
degree = 2

y_final = []
ids_final = []


In [ ]:
i = 0

model_i = all_model[i]

print(model_i['tX_tr'].shape)
print(model_i['y_tr'].shape)
print(model_i['tX_te'].shape)
print(model_i['te_id'].shape)

nSample, nFeature = model_i['tX_tr'].shape
#oneHistogram(range(0, nFeature), model_i['tX_tr'], model_i['y_tr'])

print('start learning')
best_parameter, loss_tr, loss_te = learning(model_i['tX_tr'], model_i['y_tr'], degree, lambda_[i]) #ou model_i['best_param']
model_i.update({'best_param': best_parameter})
print('learning done')

(99913, 16)
(99913,)
(227458, 16)
(227458,)
start learning
[[7.04220313 4.41176746 4.31512532 ... 1.09292951 3.4648918  4.29570593]
 [7.06975848 2.88552671 4.85736756 ... 1.45931245 1.28481519 3.70014081]
 [7.00813803 3.94268799 4.55249699 ... 1.31237868 3.65537438 4.76325028]
 ...
 [0.         4.08053295 4.12653743 ... 1.33841628 3.86342082 4.21552921]
 [6.99846489 3.01357219 4.13823385 ... 0.967364   2.56809824 4.60557011]
 [0.         4.30073523 4.1699312  ... 1.60843741 3.72858082 4.46276525]]
[[7.04220313 4.41176746 4.31512532 ... 1.09292951 3.4648918  4.29570593]
 [7.06975848 2.88552671 4.85736756 ... 1.45931245 1.28481519 3.70014081]
 [7.00813803 3.94268799 4.55249699 ... 1.31237868 3.65537438 4.76325028]
 ...
 [0.         4.08053295 4.12653743 ... 1.33841628 3.86342082 4.21552921]
 [6.99846489 3.01357219 4.13823385 ... 0.967364   2.56809824 4.60557011]
 [0.         4.30073523 4.1699312  ... 1.60843741 3.72858082 4.46276525]]
shape generated features
(99913, 60)
1891
()
(0,)
(1,

(16, 17)
(16, 18)
(16, 19)
(16, 20)
(16, 21)
(16, 22)
(16, 23)
(16, 24)
(16, 25)
(16, 26)
(16, 27)
(16, 28)
(16, 29)
(16, 30)
(16, 31)
(16, 32)
(16, 33)
(16, 34)
(16, 35)
(16, 36)
(16, 37)
(16, 38)
(16, 39)
(16, 40)
(16, 41)
(16, 42)
(16, 43)
(16, 44)
(16, 45)
(16, 46)
(16, 47)
(16, 48)
(16, 49)
(16, 50)
(16, 51)
(16, 52)
(16, 53)
(16, 54)
(16, 55)
(16, 56)
(16, 57)
(16, 58)
(16, 59)
(17, 17)
(17, 18)
(17, 19)
(17, 20)
(17, 21)
(17, 22)
(17, 23)
(17, 24)
(17, 25)
(17, 26)
(17, 27)
(17, 28)
(17, 29)
(17, 30)
(17, 31)
(17, 32)
(17, 33)
(17, 34)
(17, 35)
(17, 36)
(17, 37)
(17, 38)
(17, 39)
(17, 40)
(17, 41)
(17, 42)
(17, 43)
(17, 44)
(17, 45)
(17, 46)
(17, 47)
(17, 48)
(17, 49)
(17, 50)
(17, 51)
(17, 52)
(17, 53)
(17, 54)
(17, 55)
(17, 56)
(17, 57)
(17, 58)
(17, 59)
(18, 18)
(18, 19)
(18, 20)
(18, 21)
(18, 22)
(18, 23)
(18, 24)
(18, 25)
(18, 26)
(18, 27)
(18, 28)
(18, 29)
(18, 30)
(18, 31)
(18, 32)
(18, 33)
(18, 34)
(18, 35)
(18, 36)
(18, 37)
(18, 38)
(18, 39)
(18, 40)
(18, 41)
(18, 42)
(

(48, 55)
(48, 56)
(48, 57)
(48, 58)
(48, 59)
(49, 49)
(49, 50)
(49, 51)
(49, 52)
(49, 53)
(49, 54)
(49, 55)
(49, 56)
(49, 57)
(49, 58)
(49, 59)
(50, 50)
(50, 51)
(50, 52)
(50, 53)
(50, 54)
(50, 55)
(50, 56)
(50, 57)
(50, 58)
(50, 59)
(51, 51)
(51, 52)
(51, 53)
(51, 54)
(51, 55)
(51, 56)
(51, 57)
(51, 58)
(51, 59)
(52, 52)
(52, 53)
(52, 54)
(52, 55)
(52, 56)
(52, 57)
(52, 58)
(52, 59)
(53, 53)
(53, 54)
(53, 55)
(53, 56)
(53, 57)
(53, 58)
(53, 59)
(54, 54)
(54, 55)
(54, 56)
(54, 57)
(54, 58)
(54, 59)
(55, 55)
(55, 56)
(55, 57)
(55, 58)
(55, 59)
(56, 56)
(56, 57)
(56, 58)
(56, 59)
(57, 57)
(57, 58)
(57, 59)
(58, 58)
(58, 59)
(59, 59)
txfinal
[[1.         0.93518345 0.8680527  ... 0.46475332 0.40089171 0.3458053 ]
 [1.         0.93884272 0.56775187 ... 0.01232485 0.04401691 0.15720176]
 [1.         0.9306597  0.77575733 ... 0.55434227 0.55991136 0.56553638]
 ...
 [1.         0.         0.8028795  ... 0.65724111 0.4544477  0.31422671]
 [1.         0.92937514 0.59294591 ... 0.15262183 0.2721

In [ ]:
print(model_i['best_param'])

In [ ]:
i = 1

model_i = all_model[i]

print(model_i['tX_tr'].shape)
print(model_i['y_tr'].shape)
print(model_i['tX_te'].shape)
print(model_i['te_id'].shape)

nSample, nFeature = model_i['tX_tr'].shape
#oneHistogram(range(0, nFeature), model_i['tX_tr'], model_i['y_tr'])

print('start learning')
best_parameter, loss_tr, loss_te = learning(model_i['tX_tr'], model_i['y_tr'], degree, lambda_[i]) #ou model_i['best_param']
model_i.update({'best_param': best_parameter})
print('learning done')

In [ ]:
print(model_i['best_param'])

In [3]:
i = 2

model_i = all_model[i]

print(model_i['tX_tr'].shape)
print(model_i['y_tr'].shape)
print(model_i['tX_te'].shape)
print(model_i['te_id'].shape)

nSample, nFeature = model_i['tX_tr'].shape
#oneHistogram(range(0, nFeature), model_i['tX_tr'], model_i['y_tr'])

print('start learning')
best_parameter, loss_tr, loss_te = learning(model_i['tX_tr'], model_i['y_tr'], degree, lambda_[i]) #ou model_i['best_param']
model_i.update({'best_param': best_parameter})
print('learning done')

(72543, 24)
(72543,)
(165442, 24)
(165442,)
start learning
[[7.03744053 3.9637612  4.51630618 ... 2.83685377 1.90805992 3.99404529]
 [6.99369809 2.67759099 3.96687097 ... 3.30192938 1.74466786 4.90109569]
 [7.04643316 3.39658677 4.61958578 ... 3.32744319 1.72828705 4.79292695]
 ...
 [0.         3.66568759 4.16495834 ... 3.85485989 1.79425635 4.9722132 ]
 [7.03003928 1.59290194 4.10183312 ... 4.65723119 1.80467569 3.26392567]
 [7.10416053 3.87444574 4.03413444 ... 1.23051736 1.69414664 4.74452335]]
[[7.03744053 3.9637612  4.51630618 ... 2.83685377 1.90805992 3.99404529]
 [6.99369809 2.67759099 3.96687097 ... 3.30192938 1.74466786 4.90109569]
 [7.04643316 3.39658677 4.61958578 ... 3.32744319 1.72828705 4.79292695]
 ...
 [0.         3.66568759 4.16495834 ... 3.85485989 1.79425635 4.9722132 ]
 [7.03003928 1.59290194 4.10183312 ... 4.65723119 1.80467569 3.26392567]
 [7.10416053 3.87444574 4.03413444 ... 1.23051736 1.69414664 4.74452335]]
shape generated features
(72543, 96)
4753
txfinal
[[1

In [4]:
print(model_i['best_param'])

1e-07


In [ ]:
# print best parameter for each model
for model_i in all_model:
    print(model_i['best_param'])