In [1]:
from proj1_helpers import *
import matplotlib.pyplot as plt
import numpy as np
from implementation import *
from Visualization import *
from data_preproc import preprocessing
from features_func import generate_features
from Learning import learning

In [2]:
train_path = 'data/train.csv'
y, tX, ids = load_csv_data(train_path, sub_sample=False)
nSample_tr, nFeature_tr = tX.shape

test_path = 'data/test.csv'
_, tX_te, ids_te = load_csv_data(test_path, sub_sample=False)
y_te = np.zeros((tX_te.shape[0],))
nSample_te, nFeature_te = tX.shape

complete_tX = np.vstack((tX,tX_te))
complete_y = np.append(y,y_te)
complete_ids = np.append(ids,ids_te)

model0, model1, model2 = preprocessing(complete_tX,complete_y,complete_ids)

all_model = [model0, model1, model2]


lambda_ = np.logspace(-10, -4, 50)
degree = 1

y_final = []
ids_final = []


for model_i in all_model:
    print(model_i['tX_tr'].shape)
    print(model_i['y_tr'].shape)
    print(model_i['tX_te'].shape)
    print(model_i['te_id'].shape)

    nSample, nFeature = model_i['tX_tr'].shape
    #oneHistogram(range(0, nFeature), model_i['tX_tr'], model_i['y_tr'])

    print('start learning')
    best_parameter, loss_tr, loss_te = learning(model_i['tX_tr'], model_i['y_tr'], degree, lambda_) #ou model_i['best_param']
    model_i.update({'best_param': best_parameter})
    print('learning done')

(99913, 16)
(99913,)
(227458, 16)
(227458,)
start learning
[[7.04220313 4.41176746 4.31512532 ... 1.09292951 3.4648918  4.29570593]
 [7.06975848 2.88552671 4.85736756 ... 1.45931245 1.28481519 3.70014081]
 [7.00813803 3.94268799 4.55249699 ... 1.31237868 3.65537438 4.76325028]
 ...
 [0.         4.08053295 4.12653743 ... 1.33841628 3.86342082 4.21552921]
 [6.99846489 3.01357219 4.13823385 ... 0.967364   2.56809824 4.60557011]
 [0.         4.30073523 4.1699312  ... 1.60843741 3.72858082 4.46276525]]
[[7.04220313 4.41176746 4.31512532 ... 1.09292951 3.4648918  4.29570593]
 [7.06975848 2.88552671 4.85736756 ... 1.45931245 1.28481519 3.70014081]
 [7.00813803 3.94268799 4.55249699 ... 1.31237868 3.65537438 4.76325028]
 ...
 [0.         4.08053295 4.12653743 ... 1.33841628 3.86342082 4.21552921]
 [6.99846489 3.01357219 4.13823385 ... 0.967364   2.56809824 4.60557011]
 [0.         4.30073523 4.1699312  ... 1.60843741 3.72858082 4.46276525]]
shape generated features
(99913, 60)
61
()
(0,)
(1,)


5.179474679231202e-09
6.866488450042998e-09
9.102981779915227e-09
1.206792640639329e-08
1.5998587196060573e-08
2.1209508879201927e-08
2.8117686979742307e-08
3.7275937203149377e-08
4.9417133613238385e-08
6.551285568595509e-08
8.68511373751352e-08
1.1513953993264481e-07
1.5264179671752333e-07
2.0235896477251556e-07
2.6826957952797275e-07
3.5564803062231287e-07
4.7148663634573897e-07
6.250551925273976e-07
8.286427728546842e-07
1.0985411419875572e-06
1.4563484775012444e-06
1.9306977288832498e-06
2.5595479226995334e-06
3.3932217718953298e-06
4.498432668969444e-06
5.963623316594637e-06
7.906043210907702e-06
1.0481131341546853e-05
1.3894954943731361e-05
1.8420699693267162e-05
2.4420530945486497e-05
3.23745754281764e-05
4.291934260128778e-05
5.689866029018293e-05
7.543120063354608e-05
0.0001
learning done


In [3]:
# print best parameter for each model
for model_i in all_model:
    print(model_i['best_param'])

4.9417133613238385e-08
1.0985411419875572e-06
1.4563484775012444e-06
